from collections import defaultdict


def unify_clients_by_fiscal_name(organized_invoices):
    name_fiscal = {
        "VENTA AL PUBLICO EN GENERAL - SP": "SAUL PEREZ",
        "VENTA AL PUBLICO EN GENERAL - RB": "RAUL BOVIO GUERRERO",
        "VENTA AL PUBLICO EN GENERAL  - CF": "CARNICOS LA FORTUNA",
        "VENTA AL PUBLICO EN GENERAL - IA": "ISA ALIMENTOS",
        "VENTA AL PUBLICO EN GENERAL - RS": "LA UNION Y EZEQUIEL SERRANO",
        "VENTA AL PUBLICO EN GENERAL -AM": "ADRIAN MONTIEL PEÑA",
        "VENTA AL PUBLICO EN GENERAL - AB": "ARTURO BARRADAS",
        "VENTA AL PUBLICO EN GENERAL  - RC": "ARIADNA ANGELICA MORENO y GRUPO ARI",
        "VENTAS AL PUBLICO EN GENERAL - DG": "DON GATO",
        "VENTA AL PUBLICO EN GENERAL - IE": "IVAN ESTRADA ALVARADO",
        "VENTA AL PUBLICO EN GENERAL  - MC": "MANUEL JESUS CORONADO SOSA",
        "VENTA AL PUBLICO EN GENERAL - FL": "FRANCISCO LOPEZ",
        "VENTA AL PUBLICO EN GENERAL - ML": "MARIO LOPEZ VANZINI",
        "VENTA AL PUBLICO EN GENERAL - COP": "COPOCAR",
        "VENTA AL PUBLICO EN GENERAL - YC": "YESSICA CAICERO MURRIETA",
        "VENTA AL PUBLICO EN GENERAL - MN": "MIGUEL ANGEL NAVARRO DIAZ",
        "VENTA AL PUBLICO EN GENERAL - AQ": "AQUA",
        "VENTA AL PUBLICO EN GENERAL - COV": "COVAGO",
        "VENTA AL PUBLICO EN GENERAL - JR": "JOSE ALBERTO OLIVEROS",
        "VENTA AL PUBLICO EN GENERAL - GT": "GILDARDO TORRES",
        "VENTA AL PUBLICO EN GENERAL - MS": "MIGUEL ANGEL SANTIAGO HERNANDEZ",
        "VENTA AL PUBLICO EN GENERAL - JM": "JONATHAN MARTINEZ BUSTOS",
        "VENTA AL PUBLICO EN GENERAL - JC": "JAVIER CASTILLO",
        "VENTA AL PUBLICO EN GENERAL - JS": "JUAN SANTIAGO SANTIAGO",
        "VENTA AL PUBLICO EN GENERAL - OML": "OBRADOR Y EMPACADORA LARA",
        "VENTA AL PUBLICO EN GENERAL - FCH": "FERNANDO CHAVEZ",
        "VENTA AL PUBLICO GENERAL - OL": "OBRADOR Y EMPACADORA LARA",
        "VENTA AL PUBLICO EN GENERAL - EG": "ROSARIO GONZALEZ SERRANO",
        "VENTA AL PUBLICO EN GENERAL - JE": "JORGE ESQUIVEL CASTRO",
        "VENTA AL PUBLICO EN GENERAL - LA": "LUIS ARREGUIN",
        "VENTA AL PUBLICO EN GENERAL - AG": "ABELARDO GONZALEZ",
        "VENTA AL PUBLICO EN GENERAL - AL": "EMPACADORA ARIALY",
        "VENTA AL PUBLICO EN GENERAL - CO": "COPOCAR",
        "VENTA AL PUBLICO EN GENERAL - SHP": "SERGIO HERNANDEZ PONCE",
        "VENTA AL PUBLICO EN GENERAL - MG": "MARBUSTELL GRUPO COMERCIAL",
        "VENTA AL PUBLICO EN GENERAL - MV": "MIGUEL VALVERDE",
        "VENTA AL PUBLICO EN GENERAL  - MA": "JULIA MUÑOZ",
        "VENTA AL PUBLICO EN GENERAL - VE": "VICENTE ESTRADA",
        "VENTA AL PUBLICO EN GENERAL - JV": "JOSE ALFREDO VELA",
        "VENTA AL PUBLICO EN GENERAL - FC": "FRANCISCO COBOS"
    }

    unified_data = defaultdict(lambda: defaultdict(list))

    for client_name, currencies in organized_invoices.items():
        # Obtener el nombre fiscal del cliente
        fiscal_name = name_fiscal.get(client_name, client_name)

        for currency, invoices in currencies.items():
            # Fusionar las facturas bajo el nombre fiscal
            unified_data[fiscal_name][currency].extend(invoices)

    return unified_data

